# Generated by Django 4.2.5 on 2023-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_subtype_subsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtype',
            name='cost',
            field=models.CharField(default=1, max_length=50, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtype',
            name='period',
            field=models.CharField(default=1, max_length=50, verbose_name='Срок действия'),
            preserve_default=False,
        ),
    ]
