# Generated by Django 4.2.5 on 2023-11-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordertovar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='house_num',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_num',
        ),
    ]
