# Generated by Django 4.2.5 on 2023-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_house_num_remove_order_street_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(default=0, max_length=100, verbose_name='Квартира'),
            preserve_default=False,
        ),
    ]
