# Generated by Django 4.2.5 on 2023-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ПРИНЯТ В РАБОТУ', 'Принят в работу'), ('В СБОРКЕ', 'В сборке'), ('В ДОСТАВКЕ', 'В доставке'), ('ВЫПОЛНЕН', 'Выполнен')], max_length=20, null=True),
        ),
    ]
